version: '3.6'

services:
  client:
    build:
      context: ./ClientApp
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
    command: npm start -- --poll=100 --host 0.0.0.0 --disableHostCheck
    ports:
      - 4200:4200
    volumes:
      - ./ClientApp:/src
      - /src/ClientApp/node_modules
  web:
    build:
      target: restore
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_CLIENT=True
    command: dotnet watch run
    ports:
      - 5000:80
    volumes:
      - .:/src
      - /src/obj
      - /src/bin
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
