version: '3.4'

services:
  client:
    build:
      context: ./BarbellHero/ClientApp
      dockerfile: ./Dockerfile
      target: deps
    environment:
      - NODE_ENV=development
    command: yarn start --poll=100 --host 0.0.0.0 --disableHostCheck
    ports:
      - 4200:4200
    volumes:
      - ./BarbellHero/ClientApp:/home/app
      - ./home/app/node_modules
  web:
    build:
      target: restore
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
    command: dotnet watch run
    ports:
      - "${PORT:-5000}:80"
    volumes:
      - ./BarbellHero:/src
      - /src/obj
      - /src/bin
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
