version: '3.4'

services:
  client:
    build:
      context: ./ClientApp
      dockerfile: ./Dockerfile
      target: deps
    environment:
      - NODE_ENV=development
    command: yarn start --poll=100 --host 0.0.0.0 --disableHostCheck
    ports:
      - 4200:4200
    volumes:
      - ./ClientApp:/home/app
      - ./home/app/node_modules
  web:
    build:
      target: restore
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=${PORT:-80}
      - ASPNETCORE_URLS=http://*:$PORT 
    entrypoint: dotnet watch run
    ports:
      - "${PORT:-80}:${PORT:-80}"
    volumes:
      - .:/src
      - /src/obj
      - /src/bin
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
